"""Build fictional, publicly shareable ScopeSnap sample PDFs.
These examples use the current report information hierarchy; live reports are
generated by the ScopeSnap app from each builder's actual captured data.
"""
from pathlib import Path
from reportlab.pdfgen import canvas as pdfcanvas
from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether, PageBreak

ROOT = Path(__file__).resolve().parent.parent
INK = colors.HexColor("#1E1A16")
MUTED = colors.HexColor("#5C5348")
GOLD = colors.HexColor("#C17F3E")
LINE = colors.HexColor("#E2DDD6")
PAPER = colors.HexColor("#F5F2ED")
WHITE = colors.white

STYLES = {
    "eyebrow": ParagraphStyle("eyebrow", fontName="Helvetica-Bold", fontSize=9, leading=13, textColor=GOLD, spaceAfter=10),
    "cover": ParagraphStyle("cover", fontName="Times-Roman", fontSize=32, leading=38, textColor=INK, spaceAfter=12),
    "subtitle": ParagraphStyle("subtitle", fontName="Helvetica", fontSize=12, leading=18, textColor=MUTED, spaceAfter=27),
    "h1": ParagraphStyle("h1", fontName="Times-Roman", fontSize=23, leading=28, textColor=INK, spaceBefore=20, spaceAfter=9),
    "h2": ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=11, leading=15, textColor=GOLD, spaceBefore=14, spaceAfter=8),
    "body": ParagraphStyle("body", fontName="Helvetica", fontSize=9.6, leading=15.5, textColor=INK, spaceAfter=8),
    "small": ParagraphStyle("small", fontName="Helvetica", fontSize=8.6, leading=13, textColor=MUTED, spaceAfter=7),
    "label": ParagraphStyle("label", fontName="Helvetica-Bold", fontSize=8.5, leading=13, textColor=MUTED),
    "value": ParagraphStyle("value", fontName="Helvetica", fontSize=9.3, leading=14.5, textColor=INK),
    "meta": ParagraphStyle("meta", fontName="Helvetica", fontSize=10, leading=19, textColor=INK),
}
def P(text, style="body"):
    return Paragraph(text, STYLES[style])

def header(canvas, doc, kind):
    canvas.saveState()
    width, height = A4
    canvas.setFillColor(GOLD)
    canvas.rect(0, height-6, width, 6, fill=1, stroke=0)
    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(INK)
    canvas.drawString(20*mm, height-17*mm, "SCOPESNAP")
    canvas.setFont("Helvetica", 7.5)
    canvas.setFillColor(MUTED)
    canvas.drawRightString(width-20*mm, height-17*mm, kind.upper()+" / ILLUSTRATIVE EXAMPLE")
    canvas.setStrokeColor(LINE)
    canvas.line(20*mm, height-20*mm, width-20*mm, height-20*mm)
    canvas.line(20*mm, 17*mm, width-20*mm, 17*mm)
    canvas.setFont("Helvetica", 7.4)
    canvas.drawString(20*mm, 12*mm, "Example Building Co.  |  Fictional South Australian renovation")
    canvas.drawRightString(width-20*mm, 12*mm, "%02d" % doc.page)
    canvas.restoreState()

def cover(story, kind):
    story.extend([Spacer(1, 26*mm), P(kind.upper(), "eyebrow"),
                  P("Adelaide Hills<br/>Renovation", "cover"),
                  P("42 Example Road &middot; Hahndorf SA 5245", "subtitle")])
    meta = [
        ["PREPARED FOR", "Sam Example"],
        ["PREPARED BY", "Example Building Co."],
        ["ISSUED", "9 October 2026"],
        ["REFERENCE", "SS-EXAMPLE-01"],
    ]
    t = Table([[P(k,"label"),P(v,"meta")] for k,v in meta], colWidths=[43*mm,115*mm])
    t.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP"),("BOTTOMPADDING",(0,0),(-1,-1),9),
                          ("LINEBELOW",(0,-1),(-1,-1),1.5,GOLD)]))
    story.extend([t, Spacer(1, 23*mm)])
    note = Table([[P("SAMPLE DOCUMENT", "eyebrow")],
                  [P("This is an illustrative example, not a quotation, contract or construction specification. Photos and measurements from a real site visit would be included in the live reports.", "small")]], colWidths=[158*mm])
    note.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),PAPER),
                              ("LEFTPADDING",(0,0),(-1,-1),14),("RIGHTPADDING",(0,0),(-1,-1),14),
                              ("TOPPADDING",(0,0),(-1,0),13),("BOTTOMPADDING",(0,-1),(-1,-1),13)]))
    story.extend([note, PageBreak()])

def section(story, number, name, status, rows, owner=None, confirm=None):
    title = Table([[P(number,"eyebrow"),P(name,"h1")]], colWidths=[15*mm,143*mm])
    title.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LINEBELOW",(0,0),(-1,-1),.7,LINE)]))
    story.extend([KeepTogether([title,P(status.upper(),"small")]),Spacer(1,3*mm)])
    data = [[P(label.upper(),"label"),P(value,"value")] for label,value in rows]
    table = Table(data, colWidths=[43*mm,115*mm], hAlign="LEFT")
    table.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),5),
        ("RIGHTPADDING",(0,0),(-1,-1),8),("TOPPADDING",(0,0),(-1,-1),9),
        ("BOTTOMPADDING",(0,0),(-1,-1),9),("LINEBELOW",(0,0),(-1,-1),.5,LINE)]))
    story.append(table)
    for heading,values in (("BY OWNER",owner),("TO CONFIRM",confirm)):
        if values:
            story.append(P(heading,"h2"))
            for item in values: story.append(P("&bull; "+item))
    story.append(Spacer(1,6*mm))

def build_client():
    story=[]
    cover(story,"Client scope report")
    story.extend([P("Scope overview","h1"),
        P("Proposed renovation of the kitchen, main bathroom and laundry, with selected whole-house roofing and gutter works. The following scope describes the work understood to be included in the upcoming quotation."),
        Spacer(1,7*mm)])
    section(story,"01","Kitchen","Existing area - renovation",[
        ("Proposed works","Remove existing kitchen cabinetry, benchtops and splashback. Supply and install replacement joinery, stone benchtops and tiled splashback."),
        ("Cabinetry","Shaker-style doors with laminate finish"),
        ("Benchtops","Stone; final selection to confirm"),("Floor finish","Tiles")],
        ["Oven, induction cooktop and dishwasher supplied by owner."],
        ["Final appliance models and service connections."])
    section(story,"02","Main bathroom","Existing area - renovation",[
        ("Proposed works","Remove existing fittings and finishes. Allow for new shower, wall-hung vanity, waterproofing and tiling."),
        ("Vanity","Wall-hung with stone top"),("Shower screen","Semi-frameless")],
        confirm=["Final shower screen dimensions and tile selections."])
    section(story,"03","Laundry","Existing area - renovation",[
        ("Proposed works","Replace laundry cabinetry, trough and benchtop. Retain existing window."),
        ("Benchtop","Laminate"),("Floor finish","Tiles")])
    section(story,"04","Whole house &amp; exterior","Project-wide works",[
        ("Roofing","New Colourbond roof sheeting; final extent to confirm"),
        ("Gutters","Replace with quad-profile gutters"),
        ("Hot water","Existing system to be assessed; no replacement included unless confirmed")],
        confirm=["Roof area, flashing details and gutter/downpipe extent."])
    story.extend([P("Client review - before quotation","h1"),
        P("Please check that the proposed works, owner-supplied items and matters to confirm match your expectations. Advise the builder of changes before the quotation is finalised."),
        P("This document is an illustrative scope, not a quotation or building contract.","small")])
    write("sample-client-report.pdf",story,"Client scope report")

def build_internal():
    story=[]
    cover(story,"Internal site report")
    story.extend([P("Site briefing","h1"),
        P("Illustrative internal capture for estimating and supervision. All selections and dimensions are examples and must be verified on site before pricing, ordering or construction."),
        Spacer(1,7*mm)])
    section(story,"01","Kitchen","Existing area - renovation",[
        ("Measurements","4.20 m x 3.80 m x 2.70 m ceiling"),
        ("Scope","Full strip-out, new cabinetry, stone benchtops, tiled splashback and services adjustments."),
        ("Site notes","Check wall condition and appliance positions before final joinery set-out."),
        ("Selections","Shaker laminate cabinetry; stone benchtops; tiled splashback")],
        ["Appliances supplied by owner."],
        ["Appliance models, final cabinetry drawings and electrical requirements."])
    section(story,"02","Main bathroom","Existing area - renovation",[
        ("Measurements","3.10 m x 2.40 m x 2.70 m ceiling"),
        ("Scope","Remove fittings and finishes; waterproofing, tiling, shower screen and wall-hung vanity."),
        ("Site notes","Confirm wet-area substrate and shower-screen opening.")],
        confirm=["Shower screen dimensions, tile sizes and heights."])
    section(story,"03","Laundry","Existing area - renovation",[
        ("Measurements","2.50 m x 2.10 m x 2.70 m ceiling"),
        ("Scope","Replace cabinetry, trough and benchtop; retain window."),
        ("Site notes","Verify existing waste and plumbing condition.")])
    section(story,"04","Whole house &amp; exterior","Project-wide works",[
        ("Roof","Colourbond re-sheet proposed"),("Gutters","Quad-profile replacement"),
        ("Hot water","Existing system; assess condition")],
        confirm=["Roof quantities, flashings and gutter lengths."])
    story.append(P("Approximate estimating quantities","h1"))
    quantities=[["AREA","FLOOR m2","WALLS m2"],
        ["Kitchen","15.96","43.20"],["Main bathroom","7.44","29.70"],
        ["Laundry","5.25","24.84"],["TOTAL - GROSS","28.65","97.74"]]
    q=Table([[P(x,"label" if i==0 or i==len(quantities)-1 else "value") for x in row]
             for i,row in enumerate(quantities)],colWidths=[85*mm,35*mm,38*mm])
    q.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),PAPER),
        ("LINEBELOW",(0,0),(-1,-1),.5,LINE),("TOPPADDING",(0,0),(-1,-1),10),
        ("BOTTOMPADDING",(0,0),(-1,-1),10),("VALIGN",(0,0),(-1,-1),"TOP")]))
    story.extend([q,Spacer(1,4*mm),
        P("Gross dimensions only. Floor = length x width; walls = 2 x (length + width) x ceiling height. No deductions for openings, waste or construction tolerances.","small"),
        P("Estimator &amp; supervisor handover","h1"),
        P("Confirm all outstanding selections, existing conditions and site dimensions before pricing or procurement. In a live report, captured photographs and their captions appear with the relevant room.")])
    write("sample-internal-report.pdf",story,"Internal site report")

def write(name,story,kind):
    target=ROOT/name
    doc=SimpleDocTemplate(str(target),pagesize=A4,
        rightMargin=20*mm,leftMargin=20*mm,topMargin=28*mm,bottomMargin=23*mm,
        title="ScopeSnap - "+kind+" (illustrative example)",
        author="ScopeSnap",subject="Fictional Australian renovation report example")
    doc.build(story,onFirstPage=lambda c,d:header(c,d,kind),
              onLaterPages=lambda c,d:header(c,d,kind),
              canvasmaker=lambda *args, **kwargs: pdfcanvas.Canvas(*args, **{**kwargs, "invariant": 1}))
    assert target.stat().st_size>2000
    print(str(target.name),target.stat().st_size)

if __name__=="__main__":
    build_client()
    build_internal()
